### ISSUE TITLE
本地调试报错ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dataminingstrongly** [gcloudlab/QA#8]
报错详情：
/src/components/Generator.tsx:110
      window.removeEventListener(type, eventHandler);
      ^

ReferenceError: window is not defined
    at eval (/src/components/Generator.tsx:110:7)
    at Array.forEach (<anonymous>)
    at Array.eval (/src/components/Generator.tsx:109:16)
    at cleanNode (/node_modules/solid-js/dist/server.js:127:68)
    at Timeout.eval [as _onTimeout] (/node_modules/solid-js/dist/server.js:49:52)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.14.2
 ELIFECYCLE  Command failed with exit code 1.

**Comment by yesmore** [comment]
加个判断 ：if (typeof window !== "undefined") {}
